feature/BHT-9-wallet-connect
bictory-dev/solnames-webapp pull request #1
Opened 2024-02-10 18:57 UTC by abbas-bictory

2024-02-11 01:38 UTC, amirbictory commented on .prettierignore
> +static/flexbox.min.css
please remove this dependency ! we are using tailwindcss as css framework

2024-02-11 01:47 UTC, amirbictory reviewed
Whole styling of components should be refactored since we are using tailwindcss in the oproject.

2024-02-11 01:47 UTC, amirbictory commented on src/lib/long-text/long-text.svelte
> +<script lang="ts">
We have a components folder inside lib folder, please put components inside lib/components and if they are single files don't need to add a folder , just use the component name.

2024-02-11 01:47 UTC, amirbictory commented on src/lib/long-text/long-text.svelte
> +  export let visibleLength: number | [number, number] = 5;
why two types ?

2024-02-11 01:47 UTC, amirbictory commented on src/lib/wallet-connect/wallet-connect.svelte
> +  import Icon from '@iconify/svelte';
please sync with team about any added library , i think this one is fine .

2024-02-11 01:47 UTC, amirbictory commented on src/lib/wallet-connect/wallet-connect.svelte
> +    const { PhantomWalletAdapter, SolflareWalletAdapter, TorusWalletAdapter } = await import(
why doing this inside onMount ? you are initializing wallets in the end .

2024-02-11 01:47 UTC, amirbictory commented on src/lib/wallet-connect/wallet-connect.svelte
> +    document.body.addEventListener('click', onClick, true);
svelte has a component for body to add event.

<svelte:body on:click={clickEvent} />

2024-02-11 01:47 UTC, amirbictory requested changes
please refactor styling completely and use tailwindcss.

2024-02-16 09:04 UTC, abbas-bictory commented on src/lib/long-text/long-text.svelte
> +  export let visibleLength: number | [number, number] = 5;
This components will take a long string (like wallet address) and turns it into 0xAbcd....xyz (string+dots+string)
the visibleLength controls number of visible characters before and after dots. If you just pass a number, then the number of chars before and after dots are similar, however you can have more control over it by an array. So visibleLength =[7, 3], will show 7 chars at beginning, then some dots, and finally 3 chars at the end

2024-02-17 05:54 UTC, amirbictory requested changes

2024-02-17 05:54 UTC, amirbictory commented on yarn.lock
please remove this file and only use pnpm ,

2024-02-17 06:45 UTC, merged